Add (BASKET) on UNIQUE and SET constraints
claeis/ili2c pull request #97
Opened 2023-09-15 07:22 UTC by Philippluca

REF: [Eindeutigkeitsbedingungen auf den einzelnen Transfer#90](https://github.com/claeis/ili2c/issues/90)

2023-09-18 13:01 UTC, patrickackermann approved these changes

2023-09-18 13:01 UTC, patrickackermann commented on test/java/ch/interlis/ili2c/Interlis24/Constraints24Test.java
PP: _Basket_ und _Local_ bei allen UniquenessConstraint-Tests asserten.

2023-09-29 07:29 UTC, patrickackermann requested changes

2023-09-29 07:29 UTC, patrickackermann commented on test/data/ili24.constraints/Constraints.ili
> +            SET CONSTRAINT (BASKET) NamedSetConstraintBasket: INTERLIS.objectCount(ALL) >= 0;
REQ: Der Constraint Typ `EXISTENCE CONSTRAINT` fehlt.

2023-09-29 07:29 UTC, patrickackermann commented on test/java/ch/interlis/ili2c/Interlis24/Constraints24Test.java
> +		SetConstraint constraint = (SetConstraint) td.getElement("ModelA.TopicA.ClassA.NamedSetConstraint");
PP: Bei den anderen named constraints wird hier auch der name noch assertet.

2023-09-29 07:29 UTC, patrickackermann commented on test/java/ch/interlis/ili2c/Interlis24/Constraints24Test.java
> +		SetConstraint constraint = (SetConstraint) td.getElement("ModelA.TopicA.ClassA.NamedSetConstraintBasket");
PP: Bei den anderen named constraints wird hier auch der name noch assertet.

2023-10-03 12:36 UTC, domi-b commented on test/java/ch/interlis/ili2c/CompilerTestHelper.java
> +    public static TransferDescription GetTransferDescription(String filePath){
PP: Use camelCase for method names (also in Constraints24Test.java).

2023-10-09 06:34 UTC, patrickackermann requested changes

2023-10-09 06:34 UTC, patrickackermann commented on test/data/ili24/constraints/Constraints.ili
> +            EXISTENCE CONSTRAINT NamedExistenceConstraint2: attr1 REQUIRED IN ClassOther : attrOther;            UNIQUE attr1;
REQ: Da ist ein line break verloren gegangen.

2023-10-10 11:29 UTC, patrickackermann approved these changes

2023-10-18 11:56 UTC, claeis requested changes

2023-10-18 11:56 UTC, claeis commented on ili2c-core/src/main/java/ch/interlis/ili2c/metamodel/SetConstraint.java
> +  public boolean getBasket(){ return basket; }
"perBasket" fände ich einen treffenderen Namen

2023-10-18 11:56 UTC, claeis commented on ili2c-core/src/main/java/ch/interlis/ili2c/metamodel/UniquenessConstraint.java
> +   public void setBasket(boolean isBasket){
"perBasket" wäre besser

2023-10-18 11:56 UTC, claeis commented on test/data/ili24/constraints/Constraints.ili
> +            UNIQUE (BASKET) NamedUniqueBasketLocal: (LOCAL) attr2 : structAttr;
BASKET und LOCAL macht keinen Sinn. Das sollte zu einem Fehler führen.

2023-10-18 11:56 UTC, claeis commented on ili2c-core/src/main/antlr/ch/interlis/ili2c/parser/interlis24.g
> +		constr.setSourceLine(u.getLine());
Hier gibt es eine NPE, wenn das parsen von globalUniqueness oder localUniqueness fehlschlägt. Darum ist das Original besser.

2023-10-20 14:29 UTC, patrickackermann commented on ili2c-core/src/main/antlr/ch/interlis/ili2c/parser/interlis24.g
> +		constr.setSourceLine(u.getLine());
Das Problem am Original war, das der am Anfang der Regel erstellte constraint mit dem Resultat von globalUniqueness oder localUniqueness überschrieben wurde und somit _name_ und _perBasket_ verlorengingen. Nach meiner Einschätzung returned sowohl globalUniqueness wie auch localUniqueness immer ein constraint Objekt weshalb es nicht zu einer NPE kommen kann.

2023-10-25 12:40 UTC, merged