Add additional checks for context definitions
claeis/ili2c pull request #98
Opened 2023-10-10 10:32 UTC by domi-b

References https://github.com/claeis/ili2c/issues/91

2023-10-11 13:58 UTC, Philippluca requested changes

2023-10-11 13:58 UTC, Philippluca commented on test/java/ch/interlis/ili2c/Interlis24/GenericValueRanges24Test.java
> +        }
REQ: Diese Zeilen in `CompilerTestHelper` verpacken. z.B. in `GetCompileErrors(string)`. Da könnten wir auch asserten, dass der Compiler eine Exception geworfen hat. 
```
try { 
  ili2c.runCompiler(..); 
  assert.Fail();
} catch (Ili2cFailure){ ... }
```

2023-10-11 13:58 UTC, Philippluca commented on test/java/ch/interlis/ili2c/Interlis24/GenericValueRanges24Test.java
> +        assertTrue("expected: " + expected, errs.getErrs().get(0).getEventMsg().endsWith(expected));
PP: Prüfen ob https://github.com/claeis/iox-ili/pull/119/commits/575d68cb78bbbb25a9b83e1abbcea3bc5264bdd9 oder etwas ähnliches gebaut/wiederverwendet werden kann.

2023-10-16 11:33 UTC, Philippluca approved these changes

2023-10-18 12:41 UTC, claeis requested changes
in den ili-Dateien die zu einem Fehler führen auf der Zeile, wo etwas falsch ist den Fehler als Kommentar ergänzen

2023-10-20 05:34 UTC, merged